name: Keep Render Backend Alive

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping backend health endpoint
        run: |
          curl -s https://acsproject-lfwx.onrender.com/health
